/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as SuperAdminRouteImport } from './routes/super-admin';
import { Route as SignUpRouteImport } from './routes/sign-up';
import { Route as SignInRouteImport } from './routes/sign-in';
import { Route as NoOrganizationRouteImport } from './routes/no-organization';
import { Route as FlightsRouteImport } from './routes/flights';
import { Route as ActiveRunRouteImport } from './routes/active-run';
import { Route as SplatRouteImport } from './routes/$';
import { Route as IndexRouteImport } from './routes/index';
import { Route as OrganizationsOrganizationIdRouteImport } from './routes/organizations/$organizationId';
import { Route as OrganizationsOrganizationIdIndexRouteImport } from './routes/organizations/$organizationId/index';
import { Route as OrganizationsOrganizationIdSettingsRouteImport } from './routes/organizations/$organizationId/settings';
import { Route as OrganizationsOrganizationIdRunsRouteImport } from './routes/organizations/$organizationId/runs';
import { Route as OrganizationsOrganizationIdRequestRunReportRouteImport } from './routes/organizations/$organizationId/request-run-report';
import { Route as OrganizationsOrganizationIdReportsRouteImport } from './routes/organizations/$organizationId/reports';
import { Route as OrganizationsOrganizationIdReportTemplatesRouteImport } from './routes/organizations/$organizationId/report-templates';
import { Route as OrganizationsOrganizationIdNotificationsRouteImport } from './routes/organizations/$organizationId/notifications';
import { Route as OrganizationsOrganizationIdDriversRouteImport } from './routes/organizations/$organizationId/drivers';
import { Route as OrganizationsOrganizationIdAddRunsRouteImport } from './routes/organizations/$organizationId/add-runs';
import { Route as OrganizationsOrganizationIdDriverDriverIdRouteImport } from './routes/organizations/$organizationId/driver.$driverId';

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any);
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any);
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any);
const NoOrganizationRoute = NoOrganizationRouteImport.update({
  id: '/no-organization',
  path: '/no-organization',
  getParentRoute: () => rootRouteImport,
} as any);
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any);
const ActiveRunRoute = ActiveRunRouteImport.update({
  id: '/active-run',
  path: '/active-run',
  getParentRoute: () => rootRouteImport,
} as any);
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const OrganizationsOrganizationIdRoute =
  OrganizationsOrganizationIdRouteImport.update({
    id: '/organizations/$organizationId',
    path: '/organizations/$organizationId',
    getParentRoute: () => rootRouteImport,
  } as any);
const OrganizationsOrganizationIdIndexRoute =
  OrganizationsOrganizationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrganizationsOrganizationIdRoute,
  } as any);
const OrganizationsOrganizationIdSettingsRoute =
  OrganizationsOrganizationIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => OrganizationsOrganizationIdRoute,
  } as any);
const OrganizationsOrganizationIdRunsRoute =
  OrganizationsOrganizationIdRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => OrganizationsOrganizationIdRoute,
  } as any);
const OrganizationsOrganizationIdRequestRunReportRoute =
  OrganizationsOrganizationIdRequestRunReportRouteImport.update({
    id: '/request-run-report',
    path: '/request-run-report',
    getParentRoute: () => OrganizationsOrganizationIdRoute,
  } as any);
const OrganizationsOrganizationIdReportsRoute =
  OrganizationsOrganizationIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => OrganizationsOrganizationIdRoute,
  } as any);
const OrganizationsOrganizationIdReportTemplatesRoute =
  OrganizationsOrganizationIdReportTemplatesRouteImport.update({
    id: '/report-templates',
    path: '/report-templates',
    getParentRoute: () => OrganizationsOrganizationIdRoute,
  } as any);
const OrganizationsOrganizationIdNotificationsRoute =
  OrganizationsOrganizationIdNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => OrganizationsOrganizationIdRoute,
  } as any);
const OrganizationsOrganizationIdDriversRoute =
  OrganizationsOrganizationIdDriversRouteImport.update({
    id: '/drivers',
    path: '/drivers',
    getParentRoute: () => OrganizationsOrganizationIdRoute,
  } as any);
const OrganizationsOrganizationIdAddRunsRoute =
  OrganizationsOrganizationIdAddRunsRouteImport.update({
    id: '/add-runs',
    path: '/add-runs',
    getParentRoute: () => OrganizationsOrganizationIdRoute,
  } as any);
const OrganizationsOrganizationIdDriverDriverIdRoute =
  OrganizationsOrganizationIdDriverDriverIdRouteImport.update({
    id: '/driver/$driverId',
    path: '/driver/$driverId',
    getParentRoute: () => OrganizationsOrganizationIdRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/$': typeof SplatRoute;
  '/active-run': typeof ActiveRunRoute;
  '/flights': typeof FlightsRoute;
  '/no-organization': typeof NoOrganizationRoute;
  '/sign-in': typeof SignInRoute;
  '/sign-up': typeof SignUpRoute;
  '/super-admin': typeof SuperAdminRoute;
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRouteWithChildren;
  '/organizations/$organizationId/add-runs': typeof OrganizationsOrganizationIdAddRunsRoute;
  '/organizations/$organizationId/drivers': typeof OrganizationsOrganizationIdDriversRoute;
  '/organizations/$organizationId/notifications': typeof OrganizationsOrganizationIdNotificationsRoute;
  '/organizations/$organizationId/report-templates': typeof OrganizationsOrganizationIdReportTemplatesRoute;
  '/organizations/$organizationId/reports': typeof OrganizationsOrganizationIdReportsRoute;
  '/organizations/$organizationId/request-run-report': typeof OrganizationsOrganizationIdRequestRunReportRoute;
  '/organizations/$organizationId/runs': typeof OrganizationsOrganizationIdRunsRoute;
  '/organizations/$organizationId/settings': typeof OrganizationsOrganizationIdSettingsRoute;
  '/organizations/$organizationId/': typeof OrganizationsOrganizationIdIndexRoute;
  '/organizations/$organizationId/driver/$driverId': typeof OrganizationsOrganizationIdDriverDriverIdRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/$': typeof SplatRoute;
  '/active-run': typeof ActiveRunRoute;
  '/flights': typeof FlightsRoute;
  '/no-organization': typeof NoOrganizationRoute;
  '/sign-in': typeof SignInRoute;
  '/sign-up': typeof SignUpRoute;
  '/super-admin': typeof SuperAdminRoute;
  '/organizations/$organizationId/add-runs': typeof OrganizationsOrganizationIdAddRunsRoute;
  '/organizations/$organizationId/drivers': typeof OrganizationsOrganizationIdDriversRoute;
  '/organizations/$organizationId/notifications': typeof OrganizationsOrganizationIdNotificationsRoute;
  '/organizations/$organizationId/report-templates': typeof OrganizationsOrganizationIdReportTemplatesRoute;
  '/organizations/$organizationId/reports': typeof OrganizationsOrganizationIdReportsRoute;
  '/organizations/$organizationId/request-run-report': typeof OrganizationsOrganizationIdRequestRunReportRoute;
  '/organizations/$organizationId/runs': typeof OrganizationsOrganizationIdRunsRoute;
  '/organizations/$organizationId/settings': typeof OrganizationsOrganizationIdSettingsRoute;
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdIndexRoute;
  '/organizations/$organizationId/driver/$driverId': typeof OrganizationsOrganizationIdDriverDriverIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/$': typeof SplatRoute;
  '/active-run': typeof ActiveRunRoute;
  '/flights': typeof FlightsRoute;
  '/no-organization': typeof NoOrganizationRoute;
  '/sign-in': typeof SignInRoute;
  '/sign-up': typeof SignUpRoute;
  '/super-admin': typeof SuperAdminRoute;
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRouteWithChildren;
  '/organizations/$organizationId/add-runs': typeof OrganizationsOrganizationIdAddRunsRoute;
  '/organizations/$organizationId/drivers': typeof OrganizationsOrganizationIdDriversRoute;
  '/organizations/$organizationId/notifications': typeof OrganizationsOrganizationIdNotificationsRoute;
  '/organizations/$organizationId/report-templates': typeof OrganizationsOrganizationIdReportTemplatesRoute;
  '/organizations/$organizationId/reports': typeof OrganizationsOrganizationIdReportsRoute;
  '/organizations/$organizationId/request-run-report': typeof OrganizationsOrganizationIdRequestRunReportRoute;
  '/organizations/$organizationId/runs': typeof OrganizationsOrganizationIdRunsRoute;
  '/organizations/$organizationId/settings': typeof OrganizationsOrganizationIdSettingsRoute;
  '/organizations/$organizationId/': typeof OrganizationsOrganizationIdIndexRoute;
  '/organizations/$organizationId/driver/$driverId': typeof OrganizationsOrganizationIdDriverDriverIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/$'
    | '/active-run'
    | '/flights'
    | '/no-organization'
    | '/sign-in'
    | '/sign-up'
    | '/super-admin'
    | '/organizations/$organizationId'
    | '/organizations/$organizationId/add-runs'
    | '/organizations/$organizationId/drivers'
    | '/organizations/$organizationId/notifications'
    | '/organizations/$organizationId/report-templates'
    | '/organizations/$organizationId/reports'
    | '/organizations/$organizationId/request-run-report'
    | '/organizations/$organizationId/runs'
    | '/organizations/$organizationId/settings'
    | '/organizations/$organizationId/'
    | '/organizations/$organizationId/driver/$driverId';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/$'
    | '/active-run'
    | '/flights'
    | '/no-organization'
    | '/sign-in'
    | '/sign-up'
    | '/super-admin'
    | '/organizations/$organizationId/add-runs'
    | '/organizations/$organizationId/drivers'
    | '/organizations/$organizationId/notifications'
    | '/organizations/$organizationId/report-templates'
    | '/organizations/$organizationId/reports'
    | '/organizations/$organizationId/request-run-report'
    | '/organizations/$organizationId/runs'
    | '/organizations/$organizationId/settings'
    | '/organizations/$organizationId'
    | '/organizations/$organizationId/driver/$driverId';
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/active-run'
    | '/flights'
    | '/no-organization'
    | '/sign-in'
    | '/sign-up'
    | '/super-admin'
    | '/organizations/$organizationId'
    | '/organizations/$organizationId/add-runs'
    | '/organizations/$organizationId/drivers'
    | '/organizations/$organizationId/notifications'
    | '/organizations/$organizationId/report-templates'
    | '/organizations/$organizationId/reports'
    | '/organizations/$organizationId/request-run-report'
    | '/organizations/$organizationId/runs'
    | '/organizations/$organizationId/settings'
    | '/organizations/$organizationId/'
    | '/organizations/$organizationId/driver/$driverId';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SplatRoute: typeof SplatRoute;
  ActiveRunRoute: typeof ActiveRunRoute;
  FlightsRoute: typeof FlightsRoute;
  NoOrganizationRoute: typeof NoOrganizationRoute;
  SignInRoute: typeof SignInRoute;
  SignUpRoute: typeof SignUpRoute;
  SuperAdminRoute: typeof SuperAdminRoute;
  OrganizationsOrganizationIdRoute: typeof OrganizationsOrganizationIdRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin';
      path: '/super-admin';
      fullPath: '/super-admin';
      preLoaderRoute: typeof SuperAdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/sign-up': {
      id: '/sign-up';
      path: '/sign-up';
      fullPath: '/sign-up';
      preLoaderRoute: typeof SignUpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/sign-in': {
      id: '/sign-in';
      path: '/sign-in';
      fullPath: '/sign-in';
      preLoaderRoute: typeof SignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/no-organization': {
      id: '/no-organization';
      path: '/no-organization';
      fullPath: '/no-organization';
      preLoaderRoute: typeof NoOrganizationRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/flights': {
      id: '/flights';
      path: '/flights';
      fullPath: '/flights';
      preLoaderRoute: typeof FlightsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/active-run': {
      id: '/active-run';
      path: '/active-run';
      fullPath: '/active-run';
      preLoaderRoute: typeof ActiveRunRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/$': {
      id: '/$';
      path: '/$';
      fullPath: '/$';
      preLoaderRoute: typeof SplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/organizations/$organizationId': {
      id: '/organizations/$organizationId';
      path: '/organizations/$organizationId';
      fullPath: '/organizations/$organizationId';
      preLoaderRoute: typeof OrganizationsOrganizationIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/organizations/$organizationId/': {
      id: '/organizations/$organizationId/';
      path: '/';
      fullPath: '/organizations/$organizationId/';
      preLoaderRoute: typeof OrganizationsOrganizationIdIndexRouteImport;
      parentRoute: typeof OrganizationsOrganizationIdRoute;
    };
    '/organizations/$organizationId/settings': {
      id: '/organizations/$organizationId/settings';
      path: '/settings';
      fullPath: '/organizations/$organizationId/settings';
      preLoaderRoute: typeof OrganizationsOrganizationIdSettingsRouteImport;
      parentRoute: typeof OrganizationsOrganizationIdRoute;
    };
    '/organizations/$organizationId/runs': {
      id: '/organizations/$organizationId/runs';
      path: '/runs';
      fullPath: '/organizations/$organizationId/runs';
      preLoaderRoute: typeof OrganizationsOrganizationIdRunsRouteImport;
      parentRoute: typeof OrganizationsOrganizationIdRoute;
    };
    '/organizations/$organizationId/request-run-report': {
      id: '/organizations/$organizationId/request-run-report';
      path: '/request-run-report';
      fullPath: '/organizations/$organizationId/request-run-report';
      preLoaderRoute: typeof OrganizationsOrganizationIdRequestRunReportRouteImport;
      parentRoute: typeof OrganizationsOrganizationIdRoute;
    };
    '/organizations/$organizationId/reports': {
      id: '/organizations/$organizationId/reports';
      path: '/reports';
      fullPath: '/organizations/$organizationId/reports';
      preLoaderRoute: typeof OrganizationsOrganizationIdReportsRouteImport;
      parentRoute: typeof OrganizationsOrganizationIdRoute;
    };
    '/organizations/$organizationId/report-templates': {
      id: '/organizations/$organizationId/report-templates';
      path: '/report-templates';
      fullPath: '/organizations/$organizationId/report-templates';
      preLoaderRoute: typeof OrganizationsOrganizationIdReportTemplatesRouteImport;
      parentRoute: typeof OrganizationsOrganizationIdRoute;
    };
    '/organizations/$organizationId/notifications': {
      id: '/organizations/$organizationId/notifications';
      path: '/notifications';
      fullPath: '/organizations/$organizationId/notifications';
      preLoaderRoute: typeof OrganizationsOrganizationIdNotificationsRouteImport;
      parentRoute: typeof OrganizationsOrganizationIdRoute;
    };
    '/organizations/$organizationId/drivers': {
      id: '/organizations/$organizationId/drivers';
      path: '/drivers';
      fullPath: '/organizations/$organizationId/drivers';
      preLoaderRoute: typeof OrganizationsOrganizationIdDriversRouteImport;
      parentRoute: typeof OrganizationsOrganizationIdRoute;
    };
    '/organizations/$organizationId/add-runs': {
      id: '/organizations/$organizationId/add-runs';
      path: '/add-runs';
      fullPath: '/organizations/$organizationId/add-runs';
      preLoaderRoute: typeof OrganizationsOrganizationIdAddRunsRouteImport;
      parentRoute: typeof OrganizationsOrganizationIdRoute;
    };
    '/organizations/$organizationId/driver/$driverId': {
      id: '/organizations/$organizationId/driver/$driverId';
      path: '/driver/$driverId';
      fullPath: '/organizations/$organizationId/driver/$driverId';
      preLoaderRoute: typeof OrganizationsOrganizationIdDriverDriverIdRouteImport;
      parentRoute: typeof OrganizationsOrganizationIdRoute;
    };
  }
}

interface OrganizationsOrganizationIdRouteChildren {
  OrganizationsOrganizationIdAddRunsRoute: typeof OrganizationsOrganizationIdAddRunsRoute;
  OrganizationsOrganizationIdDriversRoute: typeof OrganizationsOrganizationIdDriversRoute;
  OrganizationsOrganizationIdNotificationsRoute: typeof OrganizationsOrganizationIdNotificationsRoute;
  OrganizationsOrganizationIdReportTemplatesRoute: typeof OrganizationsOrganizationIdReportTemplatesRoute;
  OrganizationsOrganizationIdReportsRoute: typeof OrganizationsOrganizationIdReportsRoute;
  OrganizationsOrganizationIdRequestRunReportRoute: typeof OrganizationsOrganizationIdRequestRunReportRoute;
  OrganizationsOrganizationIdRunsRoute: typeof OrganizationsOrganizationIdRunsRoute;
  OrganizationsOrganizationIdSettingsRoute: typeof OrganizationsOrganizationIdSettingsRoute;
  OrganizationsOrganizationIdIndexRoute: typeof OrganizationsOrganizationIdIndexRoute;
  OrganizationsOrganizationIdDriverDriverIdRoute: typeof OrganizationsOrganizationIdDriverDriverIdRoute;
}

const OrganizationsOrganizationIdRouteChildren: OrganizationsOrganizationIdRouteChildren =
  {
    OrganizationsOrganizationIdAddRunsRoute:
      OrganizationsOrganizationIdAddRunsRoute,
    OrganizationsOrganizationIdDriversRoute:
      OrganizationsOrganizationIdDriversRoute,
    OrganizationsOrganizationIdNotificationsRoute:
      OrganizationsOrganizationIdNotificationsRoute,
    OrganizationsOrganizationIdReportTemplatesRoute:
      OrganizationsOrganizationIdReportTemplatesRoute,
    OrganizationsOrganizationIdReportsRoute:
      OrganizationsOrganizationIdReportsRoute,
    OrganizationsOrganizationIdRequestRunReportRoute:
      OrganizationsOrganizationIdRequestRunReportRoute,
    OrganizationsOrganizationIdRunsRoute: OrganizationsOrganizationIdRunsRoute,
    OrganizationsOrganizationIdSettingsRoute:
      OrganizationsOrganizationIdSettingsRoute,
    OrganizationsOrganizationIdIndexRoute:
      OrganizationsOrganizationIdIndexRoute,
    OrganizationsOrganizationIdDriverDriverIdRoute:
      OrganizationsOrganizationIdDriverDriverIdRoute,
  };

const OrganizationsOrganizationIdRouteWithChildren =
  OrganizationsOrganizationIdRoute._addFileChildren(
    OrganizationsOrganizationIdRouteChildren
  );

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ActiveRunRoute: ActiveRunRoute,
  FlightsRoute: FlightsRoute,
  NoOrganizationRoute: NoOrganizationRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SuperAdminRoute: SuperAdminRoute,
  OrganizationsOrganizationIdRoute:
    OrganizationsOrganizationIdRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
